[package]
name = "yi"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["jwangl5"]
license = "MIT"
description = "简单、快速地绘制卦象图 Draw Gua easily"
categories = ["components", "visualization", "fun"]
keywords = ["周易", "Yi", "八卦"]